services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 0:0
    restart: unless-stopped
    volumes:
      - "./config:/data"
      - "/mnt/Media/Music:/music:ro"
    ports:
      - "192.168.1.102:4533:4533"
    environment:
      ND_COVERARTPRIORITY: cover.*, folder.*, front.*, embedded
      ND_ENABLEEXTERNALSERVICES: true
      ND_DEVARTWORKMAXREQUESTS: 12
      ND_IMAGECACHESIZE: 500MB
      ND_ENABLEARTWORKPRECACHE: true
      ND_TRANSCODINGCACHESIZE: 2GB
